// src/routes/projects/+page.svelte
<script lang="ts">
	import Projects from '$lib/components/Projects.svelte';

	export let data;
</script>

<svelte:head>
	<title>CD Projects</title>
	<meta
		name="description"
		content="View Carolyn DiLoreto's past and current projects. From film editing to UX Engineering there are many skills showcased in this section of the portfolio."
	/>
</svelte:head>
<Projects projects={data.projects} />

// gatsby-old/src/pages/projects.tsx
import React, { ReactElement } from 'react';
import Projects from '../components/Projects/Projects';
import Metadata from '../components/common/Metadata';

const ProjectsPage = (): ReactElement => (
  <>
    <Metadata
      title="CD Projects"
      description="View Carolyn DiLoreto's past and current projects. From film editing to UX Engineering there are many skills showcased in this section of the portfolio."
    />
    <Projects />
  </>
);

export default ProjectsPage;
