// src/components/common/Background.jsx
import React from 'react';
import PropTypes from 'prop-types';
import Img from 'gatsby-image';
import { makeStyles } from '@material-ui/styles';

const useStyles = makeStyles({
  container: {
    position: 'fixed',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: -1,
  },
  background: {
    width: '100%',
    height: '100%',
  },
});

const Background = (props) => {
  const classes = useStyles();
  const { sizes } = props;

  return (
    <div className={classes.container}>
      <Img
        fluid={sizes}
        className={classes.background}
        alt="Background Image"
      />
    </div>
  );
};
Background.propTypes = {
  sizes: PropTypes.shape({}).isRequired,
};

export default Background;

// src/lib/Background.svelte
<script lang="ts">
	import type { Asset } from '$lib/types';
	import Image from '$lib/Image.svelte';

	export let image: Asset;
	const srcset = [480, 768, 1024, 1366, 1600, 1920];
	const formats = ['avif', 'webp', 'jpg'];
</script>

<div class="container">
	<Image {image} sizes="100vw" {srcset} />
</div>

<style>
	.container {
		background-color: var(--dark-color);
		position: fixed;
		top: 0;
		left: 0;
		right: 0;
		bottom: 0;
		z-index: -1;
	}
	:global(.container img) {
		width: 100%;
		height: 100%;
		object-fit: cover;
	}
</style>
