// src/App/Footer.jsx
import React from 'react';
import PropTypes from 'prop-types';
import Typography from '@material-ui/core/Typography';
import { withStyles } from '@material-ui/core/styles';
import SocialMedia from '../SocialMedia';

const Footer = (props) => {
  const { classes } = props;

  return (
    <footer className={classes.footer}>
      <section className={classes.content}>
        <div>
          <Typography variant="caption" color="inherit">
            Copyright &copy;
            {` ${new Date().getFullYear()} `}
            Carolyn DiLoreto
          </Typography>
          <Typography variant="caption" color="inherit">
            Designed by Carolyn DiLoreto
          </Typography>
          <Typography variant="caption" color="inherit">
            Developed by Paul DiLoreto
          </Typography>
        </div>

        <SocialMedia />
      </section>
    </footer>
  );
};

Footer.propTypes = {
  classes: PropTypes.shape({
    footer: PropTypes.string,
    content: PropTypes.string,
  }).isRequired,
};

const styles = theme => ({
  footer: {
    width: '100%',
    height: theme.spacing.unit * 11,
    position: 'absolute',
    bottom: 0,
  },
  content: {
    display: 'flex',
    flexWrap: 'wrap',
    height: '100%',
    flex: 1,
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: `0 ${theme.spacing.unit * 2}px`,
    color: theme.palette.gray[700],
  },
});

export default withStyles(styles)(Footer);

// src/lib/Footer.svelte
<script lang="ts">
	import Icon from '$lib/Icon.svelte';
	import type { SocialMedia } from '$lib/types';

	export let socialMedia: SocialMedia[];
</script>

<footer>
	<div class="copyright">
		<span>Copyright © {new Date().getFullYear()} Carolyn DiLoreto</span>
		<span>Designed by Carolyn DiLoreto</span>
		<span>Developed by Paul DiLoreto</span>
	</div>
	<div class="social-media">
		{#each socialMedia as icon}
			<Icon {icon} />
		{/each}
	</div>
</footer>

<style>
	footer {
		display: flex;
		justify-content: space-between;
		padding: 1rem var(--padding);
	}
	.copyright {
		display: flex;
		flex-direction: column;
		justify-content: center;
		font-size: 0.75rem;
		line-height: 1.25rem;
	}
	.social-media {
		display: flex;
		justify-content: center;
		align-items: center;
	}
	@media (max-width: 768px) {
		footer {
			flex-direction: column;
			align-items: center;
		}
		.copyright {
			align-items: center;
		}
		.social-media {
			margin-top: 1rem;
		}
	}
</style>
