// src/components/common/Background.tsx
import React, { ReactElement } from 'react';
import Img, { FluidObject } from 'gatsby-image';
import { makeStyles } from '@material-ui/styles';

const useStyles = makeStyles({
  container: {
    position: 'fixed',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: -1,
  },
  background: {
    width: '100%',
    height: '100%',
  },
});

interface BackgroundProps {
  sizes: FluidObject;
}

const Background = (props: BackgroundProps): ReactElement => {
  const classes = useStyles();
  const { sizes } = props;

  return (
    <div className={classes.container}>
      <Img fluid={sizes} className={classes.background} alt="Background Image" />
    </div>
  );
};

export default Background;

// src/lib/components/Background.svelte
<script lang="ts">
	import type { Asset } from '$lib/types';
	import Image from './Image.svelte';

	export let fixed = false;
	export let image: Asset;
	const srcset = [480, 768, 1024, 1366, 1600, 1920];
</script>

<div class="container" class:fixed>
	<Image {image} sizes="100vw" {srcset} />
</div>

<style>
	.container {
		background-color: var(--dark-color);
		height: 100vh;
		position: absolute;
		top: 0;
		left: 0;
		right: 0;
		bottom: 0;
		z-index: -1;
	}
	.fixed {
		position: fixed;
	}
	.container :global(img) {
		width: 100%;
		height: 100%;
		object-fit: cover;
	}
</style>
